spring:
  datasource:
    url: jdbc:mysql://188.131.161.54:3306/flowable-spring-boot?useSSL=false&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
flowable:
  #关闭定时任务JOB
  async-executor-activate: false