management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9098
  servlet:
    context-path: /demo

logging:
  level:
    root: info
    org.springframework.web: trace
#logging:
#  level:
#    com.alice: info

# 配置相关的信息
info:
  projectName: demo for Java
  name: alice
