management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9098
  servlet:
    context-path: /demo

logging:
  level:
    root: info
    org.springframework.web: trace
#logging:
#  level:
#    com.alice: info

# 配置相关的信息
info:
  projectName: demo for Java
  name: alice

spring:
  redis:
    database: 9
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
redis:
  database: 9
  hostname: 127.0.0.1
  port: 6379
  password:
