spring:
  boot:
    admin:
      client:
        url: http://localhost:9098
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
